apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incident-bot-docs

bases:
  - ../../base/

images:
  - name: eb129/incident-bot-docs
    newTag: v1.10.7

generatorOptions:
  disableNameSuffixHash: true
