# # Control whether or not to enable the API for the frontend
# # Disabling the API will disable all functionality for the frontend
# api:
#   enabled: true
# Options: slack
platform: slack
# The channel where incident activity is logged
digest_channel: incidents
# Roles defined here will appear as options for each incident
roles:
  incident_commander: "The Incident Commander is the decision maker during a major incident, delegating tasks and listening to input from subject matter experts in order to bring the incident to resolution. They become the highest ranking individual on any major incident call, regardless of their day-to-day rank. Their decisions made as commander are final.\\n\\nYour job as an Incident Commander is to listen to the call and to watch the incident Slack room in order to provide clear coordination, recruiting others to gather context and details. You should not be performing any actions or remediations, checking graphs, or investigating logs. Those tasks should be delegated.\\n\\nAn IC should also be considering next steps and backup plans at every opportunity, in an effort to avoid getting stuck without any clear options to proceed and to keep things moving towards resolution.\\n\\nMore information: https://response.pagerduty.com/training/incident_commander/"
  communications_liaison: "The purpose of the Communications Liaison is to be the primary individual in charge of notifying our customers of the current conditions, and informing the Incident Commander of any relevant feedback from customers as the incident progresses.\\n\\nIt's important for the rest of the command staff to be able to focus on the problem at hand, rather than worrying about crafting messages to customers.\\n\\nYour job as Communications Liaison is to listen to the call, watch the incident Slack room, and track incoming customer support requests, keeping track of what's going on and how far the incident is progressing (still investigating vs close to resolution).\\n\\nThe Incident Commander will instruct you to notify customers of the incident and keep them updated at various points throughout the call. You will be required to craft the message, gain approval from the IC, and then disseminate that message to customers.\\n\\nMore information: https://response.pagerduty.com/training/customer_liaison/"
# Severities defined here will appear as options for each incident
severities:
  sev1: 'This signifies a critical production scenario that impacts most or all users with a major impact on SLAs. This is an all-hands-on-deck scenario that requires swift action to restore operation. Customers must be notified.'
  sev2: 'This signifies a significant production degradation scenario impacting a large portion of users.'
  sev3: 'This signifies a minor production scenario that may or may not result in degradation. This situation is worth coordination to resolve quickly but does not indicate a critical loss of service for users.'
  sev4: 'This signifies an ongoing investigation. This incident has not been promoted to SEV3 yet, indicating there may be little to no impact, but the situation warrants a closer look. This is diagnostic in nature. This is the default setting for a new incident.'
# Whether or not to deliver incident update reminders for critical incidents
# This will send out a reminder message to an active incident channel at the supplied
# interval
incident_reminders:
  # Any severity in this list will have a scheduled reminder job created
  # This job will remind the channel to send out updates at the interval
  # specified rate below
  qualifying_severities:
    - sev1
  # rate determines how often reminders are sent to an incident channel
  # This is an int and is interpreted as minutes
  rate: 30
# Statuses defined here will appear as options for each incident
statuses:
  - investigating
  - identified
  - monitoring
  - resolved
# jobs:
#   # Customize jobs behavior
#   scrape_for_aging_incidents:
#     # Enabled by default - set to false to disable the job
#     enabled: true
#     # If the job is enabled, avoid sending updates for incidents with any of these statuses
#     # This is useful if using customized statuses
#     ignore_statuses: []
options:
  # Automatically invite Slack groups to newly created incidents
  # Adding this and providing a list of group names implies enabling the feature
  # auto_invite_groups:
  #   # List of group names as configured in Slack
  #   - my-slack-group
  #   - my-other-slack-group
  # By default, channel names are prefixed inc-YYYYMMDDHM-
  # You can override this behavior here.
  channel_naming:
    # The start of the channel name prefix.
    # inc by default
    channel_name_prefix: incd
    # The formatting for the timestamp
    # %Y%m%d%H%M by default
    # The value must follow datetime valid strings.
    time_format_in_channel_name: '%Y-%m-%d'
  # The topic that will be set on all incident channels
  channel_topic:
    default: 'This is the default incident channel topic. You can edit it in settings.'
    # If set to true, set the channel topic to the meeting link. This will override channel_topic.
    set_to_meeting_link: true
  # If not using Zoom auto-create
  meeting_link: 'https://zoom.us'
  # Allow creation of an incident by reacting to a message
  # The value is the name of the reacji that will trigger the action
  # It must exist in your workspace
  # create_from_reaction: create-incident
  # Ignore logging for requests from the following user-agents
  skip_logs_for_user_agent:
    # Kubernetes health check user-agent
    - kube-probe
    # AWS ELB health check user-agent
    - ELB-HealthChecker/2.0
  # App home only shows 5 most recent incidents by default - this can be supplied and adjusted
  # Note that setting it too high may cause errors due to limitations in the Slack API for blocks in messages
  show_most_recent_incidents_app_home_limit: 2
  # Timezone to use for logging, etc.
  timezone: UTC
integrations:
  {}
  # Secret data is provided as environment variables for integrations
  # Only non-secret data is configured here
  # atlassian:
  # Enable Confluence integration
  # confluence:
  #   # Set to true to automatically create an postmortem doc
  #   auto_create_postmortem: true
  #   space: ENGINEERIN
  #   parent: Postmortems
  #   # Set a template to use for postmortems.
  #   postmortem_template_id: 123456
  # Enable Jira integration
  # jira:
  #   project: 'IN'
  #   # Issue types that will populate the list of available options when creating a Jira issue.
  #   # This will override automatically fetching issue types.
  #   # issue_types: ['Epic', 'Task']
  #   # Priorities that will populate the list of available options when creating a Jira issue.
  #   # This will override automatically fetching issue priorities.
  #   # priorities: ['High', 'Low']
  #   # Labels to apply to created issues
  #   labels:
  #     - incident-management
  # opsgenie:
  #   # Note that providing the 'team' value here will limit creation of alerts to a single team.
  #   team: oncalls
  # Simply provide an empty dict to enable PagerDuty
  # pagerduty: {}
  # Enable Statuspage integration
  # statuspage:
  #   # The public URL of the Statuspage.
  #   url: https://status.mydomain
  #   # Which Slack groups have permissions to manage Statuspage incidents?
  #   # If not provided, everyone can manage Statuspage incidents from Slack.
  #   # permissions:
  #   #   - my-slack-group
  # # Enable Zoom integration
  # zoom:
  #   # Set to true to automatically generate a Zoom meeting for each incident
  #   auto_create_meeting: true
# Links are optional
# Whatever is added here is appended to incident management context messages
links:
  []
  # - title: My Neato Link
  #   url: https://cool.com
