platform: slack
digest_channel: incidents
api:
  enabled: true
incident_reminders:
  qualifying_severities:
    - sev1
  rate: 30
jobs:
  scrape_for_aging_incidents:
    enabled: true
    ignore_statuses: ['test']
roles:
  incident_commander: 'commander'
  technical_lead: 'technical_lead'
  communications_liaison: 'communications_liaison'
severities:
  sev1: 'sev1'
  sev2: 'sev2'
  sev3: 'sev3'
  sev4: 'sev4'
statuses:
  - investigating
  - identified
  - monitoring
  - resolved
options:
  channel_topic:
    default: 'This is the default incident channel topic. You can edit it in settings.'
    set_to_meeting_link: false
  timezone: UTC
  meeting_link: 'https://zoom.us'
  skip_logs_for_user_agent:
    - kube-probe
    - ELB-HealthChecker/2.0
integrations:
  atlassian:
    confluence:
      auto_create_postmortem: true
      space: ENG
      parent: Postmortems
    jira:
      project: 'ENG'
      issue_types: ['Epic', 'Task']
      priorities: ['High', 'Low']
      labels:
        - incident-management
      auto_create_incident: false
      auto_create_incident_type: Subtask
      status_mapping:
        - incident_status: Investigating
          jira_status: Open
        - incident_status: Identified
          jira_status: In Progress
        - incident_status: Monitoring
          jira_status: In Review
        - incident_status: Resolved
          jira_status: Done
    opsgenie:
      team: oncalls
  pagerduty: {}
  statuspage:
    url: https://status.mydomain
    permissions:
      groups:
        - my-slack-group
links:
  - title: Incident Guide
    url: https://mycompany.com/incidents
  - title: My Neato Link
    url: https://cool.com
