apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: incidents.extensions.incidentbot.io
spec:
  group: extensions.incidentbot.io
  names:
    kind: Incident
    listKind: IncidentList
    plural: incidents
    shortNames:
      - inc
    singular: incident
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Creation timestamp
          jsonPath: .metadata.creationTimestamp
          name: Created
          type: date
        - description: Severity
          jsonPath: .spec.severity
          name: Severity
          type: string
        - description: Status
          jsonPath: .spec.status
          name: Status
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          required:
            - spec
          type: object
          properties:
            spec:
              required:
                - id
                - created_at
                - channel_description
                - channel_id
                - channel_name
                - is_security_incident
                - severity
                - status
              type: object
              properties:
                id:
                  type: string
                created_at:
                  type: string
                updated_at:
                  type: string
                channel_description:
                  type: string
                channel_id:
                  type: string
                channel_name:
                  type: string
                meeting_link:
                  type: string
                is_security_incident:
                  type: boolean
                last_update_sent:
                  type: string
                postmortem:
                  type: string
                roles:
                  type: object
                severity:
                  type: string
                status:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
                bp_message_ts:
                  type: string
                dig_message_ts:
                  type: string
                sp_message_ts:
                  type: string
                sp_incident_id:
                  type: string
                sp_incident_data:
                  type: object
                jira_issues:
                  items:
                    type: string
                  type: array
                pagerduty_incidents:
                  items:
                    type: string
                  type: array
      served: true
      storage: true
